# -*- coding: utf-8 -*-
"""diabetes_project_dl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mAFOY8Ye5PSJPNYEaTGTA0Ki4A3CtPHh

# Import Libraries


In this cell, I'm importing all the libraries I'll need throughout this notebook. Nothing runs here — I'm just loading the tools upfront so everything is ready when I need it later.

---

## Libraries I'm Bringing In

### Data Handling
- **pandas** — for loading, cleaning, and manipulating my dataset
- **numpy** — for numerical operations and array handling

### Visualization
- **matplotlib** — for plotting charts and graphs
- **seaborn** — for cleaner, more polished statistical visualizations

### Classical Machine Learning (scikit-learn)
- **train_test_split** — to split my data into training and testing sets
- **StandardScaler** — to normalize my features before feeding them into a model
- **LogisticRegression** — for classification tasks
- **LinearRegression** — for regression tasks
- **Metrics** — to evaluate model performance (MAE, MSE, R², confusion matrix, classification report)

### Deep Learning
- **PyTorch (torch)** — the core deep learning framework I'll use to build a neural network
- **torch.nn** — gives me access to layers, activations, and loss functions
- **DataLoader & TensorDataset** — for batching and feeding data efficiently into the neural network during training

---

## End-of-Cell Checks

At the end of the cell, I'm running three quick checks:

1. Confirming everything imported without errors
2. Printing the PyTorch version I'm running
3. Checking whether a GPU is available — if `True`, training will be significantly faster

---

## Summary

This cell is purely setup. Once it runs cleanly, I'm ready to move on to loading data and building models.
"""

# ============================================================
# Cell 1: Import Libraries
# All the tools we need for data handling, modeling, and plots
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

print("All libraries imported successfully.")
print("PyTorch version:", torch.__version__)
print("GPU available:", torch.cuda.is_available())

"""All libraries loaded successfully. We are running PyTorch 2.10 with CUDA available, confirming the A100 GPU is active and ready. This means our neural networks will train on GPU, which will significantly speed up the training process compared to CPU.

# Download and Load the Dataset

In this cell, I'm pulling in the dataset I'll be working with and loading it into memory so I can start exploring it.

---

## Step by Step

### Importing kagglehub
The UCI server where this dataset originally lives was unavailable, so instead I'm using **kagglehub** — a Python package that lets me download datasets directly from Kaggle into my environment.

### Downloading the Dataset
I'm downloading the **Diabetes Health Indicators Dataset** from Kaggle. Once it's downloaded, kagglehub returns the local path where the files were saved, and I'm printing that path just to confirm where it landed.

### Loading it into a DataFrame
I'm reading the specific CSV file from that downloaded path into a **pandas DataFrame** called `df`. This is now my main working object — everything from here on will be done on `df`.

### Quick Sanity Checks
At the end I'm running two checks:

- **Shape** — tells me how many rows and columns the dataset has, so I know the scale of what I'm working with
- **df.head()** — shows me the first 5 rows so I can visually confirm the data loaded correctly and get a feel for what the columns look like

---

## Summary

By the end of this cell, my dataset is downloaded, loaded, and I've done a first glance at it. I'm ready to start understanding and cleaning it in the next steps.
"""

# ============================================================
# Cell 2: Download and Load the Dataset
# UCI server was unavailable so we use kagglehub to fetch
# the same dataset directly into the Colab environment
# ============================================================

import kagglehub

path = kagglehub.dataset_download("alexteboul/diabetes-health-indicators-dataset")
print("Dataset downloaded to:", path)

df = pd.read_csv(path + "/diabetes_binary_health_indicators_BRFSS2015.csv")

print("Shape:", df.shape)
print("\nFirst 5 rows:")
df.head()

"""The dataset loaded successfully with 253,680 rows and 22 columns, which matches what was reported in the UC Irvine repository. Looking at the first 5 rows, we can see that most features are binary (0 or 1), such as HighBP, HighChol, Smoker, and Stroke. A few features are ordinal or continuous, such as BMI, Age, GenHlth, and Income. The target variable Diabetes_binary is in the first column. No immediate data quality issues are visible at this stage.

# Explore the Data


Before I touch anything or build any model, I'm doing a first proper look at my data. I need to understand its quality, its balance, and its structure.

---

## Step by Step

### Checking for Missing Values
I'm checking every column for null or missing values. This tells me whether I need to handle any gaps in the data before moving forward. If any column comes back with a number greater than zero, I'll need to deal with it — either by filling or dropping.

### Checking Class Balance
Since my target column is `Diabetes_binary` — meaning it's either 0 (no diabetes) or 1 (diabetes) — I need to know how evenly split those two classes are.

I'm checking this in two ways:
- **Raw counts** — the actual number of rows in each class
- **Normalized (proportions)** — what percentage of the dataset each class makes up

This matters because if one class heavily outnumbers the other, my model could end up biased — predicting the majority class most of the time and still looking accurate on paper.

### Basic Statistics
I'm running `df.describe()` which gives me a summary of every numerical column — things like the minimum, maximum, mean, and standard deviation. This gives me a feel for the range and spread of my features and helps me spot anything obviously off, like values that don't make sense for the domain.

---

## Summary

By the end of this cell, I know whether my data has any missing values, whether my classes are balanced or skewed, and what the general shape of my features looks like. This is what guides every decision I make going forward.
"""

# ============================================================
# Cell 3: Explore the Data
# Check for missing values, class balance, and basic stats
# ============================================================

# Missing values
print("Missing values per column:")
print(df.isnull().sum())

# Class distribution for diabetes target
print("\nClass distribution (Diabetes_binary):")
print(df["Diabetes_binary"].value_counts())
print(df["Diabetes_binary"].value_counts(normalize=True).round(3))

# Basic statistics
print("\nBasic statistics:")
print(df.describe())

"""The data is completely clean with zero missing values across all 22 columns,
which is expected since this is a pre-processed version of the CDC BRFSS survey.

The class distribution reveals a significant imbalance — 86.1% of respondents
have no diabetes while only 13.9% have diabetes or prediabetes. This is a
critical finding because a naive model that always predicts "no diabetes" would
achieve 86% accuracy without learning anything useful. This is exactly why we
prioritize recall over accuracy for the classification task.

Looking at the basic statistics, BMI ranges from 12 to 98 with a mean of 28.4,
which is consistent with a real-world population. Most binary features like
HighBP, HighChol, and Smoker have means between 0 and 1 as expected. Age is
encoded as an ordinal value from 1 to 13 representing age groups rather than
actual age in years.

# Visualize Class Imbalance

I already checked the class balance numerically in Cell 3. Now I'm doing the same thing but visually — because a chart makes the imbalance immediately obvious in a way raw numbers don't.

---

## Step by Step

### Setting Up the Plot
I'm creating a figure with a specific size (6x4 inches) to keep it clean and readable.

### Drawing the Bar Chart
I'm pulling the class counts from my `Diabetes_binary` column and plotting them as two bars — one for **No Diabetes** in steel blue, one for **Diabetes/Prediabetes** in crimson. The color difference makes the two classes instantly distinguishable.

### Adding Count Labels on Top of the Bars
I'm looping through both bars and placing the exact count number just above each one, formatted with commas for readability. This way I don't have to look at the y-axis to know the actual numbers — they're right there on the chart.

### Saving and Displaying
I'm saving the plot as a PNG file at 150 DPI so I have a clean copy of it, then displaying it inline in the notebook.

---

## Summary

By the end of this cell, I have a clear visual confirmation of how balanced or imbalanced my dataset is between diabetic and non-diabetic cases. If one bar is significantly taller than the other, that's something I'll need to account for when building and evaluating my models.
"""

# ============================================================
# Cell 4: Visualize Class Imbalance
# Plot how many diabetic vs non-diabetic cases exist
# ============================================================

fig, ax = plt.subplots(figsize=(6, 4))

counts = df["Diabetes_binary"].value_counts()
ax.bar(["No Diabetes", "Diabetes/Prediabetes"], counts.values, color=["steelblue", "crimson"])
ax.set_title("Class Distribution - Diabetes Status")
ax.set_ylabel("Count")
ax.set_xlabel("Class")

for i, v in enumerate(counts.values):
    ax.text(i, v + 1000, f"{v:,}", ha="center", fontweight="bold")

plt.tight_layout()
plt.savefig("class_distribution.png", dpi=150)
plt.show()

"""The bar chart makes the class imbalance immediately clear. We have 218,334
non-diabetic cases compared to only 35,346 diabetic cases. This 6:1 ratio
means our models need special handling — specifically class weighting during
training — to avoid being biased toward always predicting the majority class.
Without this correction, the model would appear to perform well on accuracy
while completely failing to detect actual diabetic patients.

# Prepare Data for Classification

This is where I start actually preparing my data to be fed into a model. Specifically, I'm getting everything ready for my **classification task** — predicting whether someone has diabetes or not.

---

## Step by Step

### Separating Features and Target
I'm splitting my DataFrame into two parts:
- **X_clf** — everything except the target column. These are my 21 input features the model will learn from.
- **y_clf** — just the `Diabetes_binary` column. This is what I'm trying to predict.

### Splitting into Train and Test Sets
I'm dividing my data into a **training set (80%)** and a **testing set (20%)** using `train_test_split`.

Two important things I'm doing here:
- **random_state=42** — locks the split so it's reproducible. Every time I run this, I get the same split.
- **stratify=y_clf** — this ensures the ratio of diabetic to non-diabetic cases is preserved in both the train and test sets. Given the class imbalance I saw earlier, this is important — without it, one set could end up with a very different distribution than the other.

### Scaling the Features
I'm applying **StandardScaler** to normalize my features — meaning every column gets rescaled to have a mean of 0 and a standard deviation of 1.

One critical thing I'm being careful about here:
- I'm calling **fit_transform** on the training data — this means the scaler learns the mean and standard deviation from the training set only.
- I'm calling **transform** on the test data — applying those same training statistics to the test set, without letting the test data influence the scaling at all.

This is important because in a real scenario, test data represents unseen data. If I scaled using the full dataset, I'd be leaking information from the test set into my training process.

### Confirming the Output
At the end I'm printing the shape of both sets just to confirm the split happened correctly and the dimensions look right.

---

## Summary

By the end of this cell, my classification data is fully prepared — split, stratified, and scaled — and ready to be fed into a model.
"""

# ============================================================
# Cell 5: Prepare Data for Classification (RQ1)
# Target: Diabetes_binary | Features: all other 21 columns
# ============================================================

X_clf = df.drop(columns=["Diabetes_binary"])
y_clf = df["Diabetes_binary"]

X_clf_train, X_clf_test, y_clf_train, y_clf_test = train_test_split(
    X_clf, y_clf,
    test_size=0.2,
    random_state=42,
    stratify=y_clf        # keeps class ratio the same in train and test
)

scaler_clf = StandardScaler()
X_clf_train_s = scaler_clf.fit_transform(X_clf_train)
X_clf_test_s  = scaler_clf.transform(X_clf_test)

print("Classification data ready.")
print("Train size:", X_clf_train_s.shape)
print("Test size: ", X_clf_test_s.shape)

"""The classification dataset is split into 202,944 training samples and 50,736 test samples, maintaining the 80/20 ratio. Stratification ensures that both splits have the same 86/14 class distribution as the full dataset. StandardScaler is fit only on the training data and then applied to the test data — this is important because fitting on the test data would leak information and give us an overly optimistic evaluation.

# Prepare Data for Regression

Same preparation process as Cell 5, but this time for my **regression task** — instead of predicting a class, I'm predicting a continuous number, specifically **BMI**.

---

## Step by Step

### Separating Features and Target
I'm splitting the DataFrame differently this time:
- **X_reg** — everything except BMI and Diabetes_binary. I'm dropping both because BMI is my target, and Diabetes_binary was my classification target so it doesn't belong here either.
- **y_reg** — just the `BMI` column. This is the number I'm trying to predict.

### Splitting into Train and Test Sets
Same 80/20 split with the same `random_state=42` for reproducibility.

One thing worth noting — I'm **not using stratify here**. That's intentional. Stratification is for classification where you have discrete classes to balance. BMI is a continuous value, so stratification doesn't apply.

### Scaling the Features
Exact same approach as Cell 5 — fit the scaler on training data only, then apply it to the test set. Same reasoning applies: I don't want the test data influencing how the scaler is calibrated.

### Confirming the Output
Printing the shapes of both sets to verify everything looks correct before moving on.

---

## Summary

By the end of this cell, I have a completely separate, clean data pipeline ready for my regression task — independent from the classification setup in Cell 5. Both tasks are now prepped and ready for modeling.
"""

# ============================================================
# Cell 6: Prepare Data for Regression (RQ2)
# Target: BMI | Features: all other columns except Diabetes_binary
# ============================================================

X_reg = df.drop(columns=["BMI", "Diabetes_binary"])
y_reg = df["BMI"]

X_reg_train, X_reg_test, y_reg_train, y_reg_test = train_test_split(
    X_reg, y_reg,
    test_size=0.2,
    random_state=42
)

scaler_reg = StandardScaler()
X_reg_train_s = scaler_reg.fit_transform(X_reg_train)
X_reg_test_s  = scaler_reg.transform(X_reg_test)

print("Regression data ready.")
print("Train size:", X_reg_train_s.shape)
print("Test size: ", X_reg_test_s.shape)

"""The regression dataset is split into 202,944 training samples and 50,736 test
samples with 20 input features. We dropped both BMI (our target) and
Diabetes_binary to keep the two tasks completely separate. The same scaling
approach is applied — StandardScaler is fit on training data only and then
used to transform the test data.

# Baseline Classification with Logistic Regression

I'm training my first model — a simple **Logistic Regression** — as a baseline for my classification task. The goal here isn't to get the best possible result, it's to establish a reference point that anything more complex needs to beat.

---

## Step by Step

### Training the Model
I'm initializing a Logistic Regression model with two settings:
- **max_iter=1000** — by default sklearn only runs 100 iterations, which often isn't enough for this size of dataset and causes a convergence warning. I'm bumping it to 1000 to give the model enough room to fully converge.
- **random_state=42** — for reproducibility.

I then call `.fit()` on my scaled training data, which is where the actual learning happens.

### Making Predictions
Once trained, I'm running the model on my **test set** — the data it has never seen — and storing the predictions in `y_pred_lr`.

### Evaluating with a Classification Report
I'm printing a full classification report which gives me four key metrics broken down by class:

- **Precision** — of everything the model predicted as Diabetes, how many actually were
- **Recall** — of all actual Diabetes cases, how many did the model catch
- **F1-score** — the balance between precision and recall, a single number that summarizes both
- **Support** — how many actual samples exist in each class

---

## Summary

By the end of this cell, I have a trained baseline classifier and a clear picture of how it performs. Every model I build after this needs to do better than these numbers to justify the added complexity.
"""

# ============================================================
# Cell 7: Baseline Classification - Logistic Regression
# Simple, interpretable baseline model to beat
# ============================================================

lr_clf = LogisticRegression(max_iter=1000, random_state=42)
lr_clf.fit(X_clf_train_s, y_clf_train)

y_pred_lr = lr_clf.predict(X_clf_test_s)

print("=== Logistic Regression - Classification Report ===")
print(classification_report(y_clf_test, y_pred_lr,
                             target_names=["No Diabetes", "Diabetes"]))

"""The logistic regression baseline confirms exactly what we expected. The overall accuracy looks decent at 86%, but this is misleading — the model is simply predicting "no diabetes" most of the time, which is easy given the class imbalance.

The recall for the diabetic class is only 0.16, meaning the model misses 84% of actual diabetic patients. In a real medical setting this would be unacceptable. This result sets our baseline and makes clear that we need a better approach. Our neural networks will use class weighting to directly address this problem.

# Simple Neural Network for Classification

I'm building and training my first neural network for the classification task. This steps up the complexity from the Logistic Regression baseline in Cell 7 to see if a neural network can do better.

---

## Step by Step

### Defining the Model Architecture
I'm creating a class called `SimpleClassifierNN` that defines the structure of my network. It has:

- **Input layer → 64 neurons** with a **ReLU activation** — this is the hidden layer where the model learns non-linear patterns in the data
- **64 neurons → 1 output neuron** with a **Sigmoid activation** — this squashes the final output to a value between 0 and 1, which I can interpret as a probability of having diabetes

The `forward` method defines how data flows through the network. The `.squeeze()` at the end just removes an unnecessary extra dimension from the output so the shape matches my labels.

### Defining the Training Function
I'm writing a reusable `train_classifier` function that handles the entire training loop. Here's what happens inside it:

- **TensorDataset & DataLoader** — I'm wrapping my data so PyTorch can feed it into the model in batches of 512 rows at a time, shuffled each epoch
- **Adam optimizer** — handles updating the model weights after each batch. It's adaptive and generally works well out of the box
- **BCELoss** — Binary Cross Entropy Loss, the standard loss function for binary classification problems
- **Training loop** — for each epoch, I loop through every batch, make predictions, calculate the loss, backpropagate the error, and update the weights. I track the average loss per epoch and print it so I can see the model improving over time

### Training the Model
I'm pulling the number of input features from my training data, initializing the model, and passing everything into the training function for 20 epochs.

### Evaluating the Model
After training I switch the model to **eval mode** and run it on the test set inside a `torch.no_grad()` block — this tells PyTorch not to track gradients since I'm just making predictions, not training. Any output above 0.5 gets classified as Diabetes, anything below as No Diabetes. I then print the same classification report as Cell 7 so I can directly compare the results.

---

## Summary

By the end of this cell, I have a trained neural network and a clear performance comparison against my Logistic Regression baseline. I can see whether the added complexity of a neural network actually translates to better predictions on this dataset.
"""

# ============================================================
# Cell 8: Simple Neural Network - Classification
# One hidden layer with ReLU activation
# ============================================================

class SimpleClassifierNN(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.network(x).squeeze()


def train_classifier(model, X_train, y_train, epochs=20, learning_rate=0.001):
    """Train a binary classification neural network and return loss history."""

    dataset = TensorDataset(
        torch.FloatTensor(X_train),
        torch.FloatTensor(y_train.values)
    )
    loader    = DataLoader(dataset, batch_size=512, shuffle=True)
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
    loss_fn   = nn.BCELoss()
    loss_history = []

    model.train()
    for epoch in range(epochs):
        epoch_loss = 0
        for X_batch, y_batch in loader:
            optimizer.zero_grad()
            predictions = model(X_batch)
            loss = loss_fn(predictions, y_batch)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()

        avg_loss = epoch_loss / len(loader)
        loss_history.append(avg_loss)
        print(f"Epoch {epoch+1:02d}/{epochs} - Loss: {avg_loss:.4f}")

    return model, loss_history


input_dim = X_clf_train_s.shape[1]
simple_clf_nn = SimpleClassifierNN(input_dim)
simple_clf_nn, simple_clf_losses = train_classifier(simple_clf_nn, X_clf_train_s, y_clf_train)

simple_clf_nn.eval()
with torch.no_grad():
    raw_preds = simple_clf_nn(torch.FloatTensor(X_clf_test_s))
    y_pred_simple_nn = (raw_preds > 0.5).int().numpy()

print("\n=== Simple Neural Network - Classification Report ===")
print(classification_report(y_clf_test, y_pred_simple_nn,
                             target_names=["No Diabetes", "Diabetes"]))

"""# What Went Wrong and What I Fixed

## Output from the First Version

### Training Loss
```
Epoch 01/20 - Loss: 0.3562
Epoch 02/20 - Loss: 0.3138
Epoch 03/20 - Loss: 0.3123
Epoch 04/20 - Loss: 0.3115
Epoch 05/20 - Loss: 0.3111
Epoch 06/20 - Loss: 0.3109
Epoch 07/20 - Loss: 0.3107
Epoch 08/20 - Loss: 0.3105
Epoch 09/20 - Loss: 0.3102
Epoch 10/20 - Loss: 0.3101
Epoch 11/20 - Loss: 0.3101
Epoch 12/20 - Loss: 0.3098
Epoch 13/20 - Loss: 0.3097
Epoch 14/20 - Loss: 0.3097
Epoch 15/20 - Loss: 0.3096
Epoch 16/20 - Loss: 0.3094
Epoch 17/20 - Loss: 0.3095
Epoch 18/20 - Loss: 0.3094
Epoch 19/20 - Loss: 0.3093
Epoch 20/20 - Loss: 0.3093
```

The loss drops sharply in the first two epochs, then essentially flatlines from Epoch 3 onward. This is a sign the model converged very early and stopped meaningfully learning — a red flag that something structural is off.

### Classification Report
```
                  precision    recall  f1-score   support

 No Diabetes       0.88      0.98      0.93     43667
    Diabetes       0.54      0.17      0.26      7069

    accuracy                           0.86     50736
   macro avg       0.71      0.57      0.59     50736
weighted avg       0.83      0.86      0.83     50736
```

---

## What the Output Told Me

Looking at the results, the model was heavily biased toward predicting **No Diabetes**:

- It identified No Diabetes cases with 98% recall — nearly perfect
- But it only caught **17% of actual Diabetes cases** — meaning it was missing 83% of them
- The overall accuracy looked decent at 86%, but that number is misleading given the class imbalance

The model essentially learned to predict "No Diabetes" almost every time and still looked accurate on paper because 86% of the dataset is No Diabetes anyway.

# Revised — Simple Neural Network with Class Weighting

I'm rebuilding the same neural network from Cell 8 but fixing the core problem I identified — the model was ignoring the minority class. This revised version explicitly tells the model to take Diabetes cases more seriously during training.

---

## Step by Step

### Computing the Class Weight
Before anything else, I'm calculating a `pos_weight` — the ratio of No Diabetes samples to Diabetes samples. Since the split is roughly 86/14, this gives me a weight of around 6, meaning the model will be penalized approximately 6x more for missing a Diabetes case than for missing a No Diabetes case.

### Switching the Loss Function
I'm replacing `BCELoss` with `BCEWithLogitsLoss` and passing in that `pos_weight`. This is what actually enforces the penalty — the loss function now treats false negatives on the minority class as significantly more costly.

### Removing Sigmoid from the Architecture
Because `BCEWithLogitsLoss` applies Sigmoid internally as part of its math, I'm rebuilding the model without it. If I kept Sigmoid in the architecture, it would get applied twice — once by the model, once by the loss function — which would break the calculation entirely. So the final layer now outputs a raw logit with no activation.

### Training Loop
Everything else in the training loop stays the same — Adam optimizer, batches of 512, 20 epochs, tracking loss per epoch.

### Adjusting the Prediction Threshold
Since the model now outputs raw logits instead of probabilities, I can no longer threshold at 0.5. Instead I threshold at **0.0** — anything above zero is Diabetes, anything below is No Diabetes. Mathematically this is identical to the 0.5 threshold on a Sigmoid output.

---

## Summary

This revised cell keeps the same architecture but corrects the training process to account for class imbalance. The model now has an explicit incentive to catch Diabetes cases rather than defaulting to the majority class every time.
"""

# ============================================================
# Cell 8 (revised): Simple Neural Network - Classification
# Added class weighting to handle the 86/14 class imbalance
# ============================================================

class SimpleClassifierNN(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.network(x).squeeze()


def train_classifier(model, X_train, y_train, epochs=20, learning_rate=0.001):
    """Train a binary classification neural network with class weighting."""

    # Weight the positive class (diabetes) higher to compensate for imbalance
    pos_weight = torch.tensor([(y_train == 0).sum() / (y_train == 1).sum()])

    dataset   = TensorDataset(
        torch.FloatTensor(X_train),
        torch.FloatTensor(y_train.values)
    )
    loader    = DataLoader(dataset, batch_size=512, shuffle=True)
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
    loss_fn   = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
    loss_history = []

    model.train()
    for epoch in range(epochs):
        epoch_loss = 0
        for X_batch, y_batch in loader:
            optimizer.zero_grad()
            predictions = model(X_batch)
            loss = loss_fn(predictions, y_batch)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()

        avg_loss = epoch_loss / len(loader)
        loss_history.append(avg_loss)
        print(f"Epoch {epoch+1:02d}/{epochs} - Loss: {avg_loss:.4f}")

    return model, loss_history


# Rebuild model without Sigmoid since BCEWithLogitsLoss handles it internally
class SimpleClassifierNN(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 1)
        )

    def forward(self, x):
        return self.network(x).squeeze()


input_dim     = X_clf_train_s.shape[1]
simple_clf_nn = SimpleClassifierNN(input_dim)
simple_clf_nn, simple_clf_losses = train_classifier(simple_clf_nn, X_clf_train_s, y_clf_train)

simple_clf_nn.eval()
with torch.no_grad():
    raw_preds        = simple_clf_nn(torch.FloatTensor(X_clf_test_s))
    y_pred_simple_nn = (raw_preds > 0.0).int().numpy()  # threshold at 0 since no sigmoid

print("\n=== Simple Neural Network - Classification Report ===")
print(classification_report(y_clf_test, y_pred_simple_nn,
                             target_names=["No Diabetes", "Diabetes"]))

"""Adding class weighting completely changed the results. Recall jumped from 0.16
to 0.80, meaning we are now correctly identifying 80% of diabetic patients
instead of just 16%. The loss starting at 0.91 instead of 0.31 confirms the
class weighting is active — the model is now penalizing missed diabetic cases
roughly 6 times more than missed non-diabetic cases, which directly reflects
the 86/14 class ratio in the data.

Precision dropped to 0.30 which is an expected tradeoff. We are casting a wider
net to catch more diabetic cases, which brings in more false positives. In a
medical screening context this is the correct tradeoff — a false positive means
extra tests, a false negative means a missed diagnosis with potentially serious
consequences.

# Deep Neural Network for Classification

I'm stepping up the complexity from the simple one-hidden-layer network in Cell 8 to a proper deep neural network. The goal is to give the model more capacity to learn complex patterns in the data, while also adding regularization to stop it from overfitting.

---

## Step by Step

### The Architecture
Instead of one hidden layer I now have three, progressively narrowing down in size:

- **Input → 128 neurons → ReLU → Dropout**
- **128 → 64 neurons → ReLU → Dropout**
- **64 → 32 neurons → ReLU**
- **32 → 1 output** (raw logit, no activation)

This funnel structure is intentional — each layer compresses the representation further, forcing the model to extract only the most important patterns at each stage.

### Dropout Layers
After the first two hidden layers I'm applying **Dropout at 30%**. During training, this randomly switches off 30% of neurons in that layer on each forward pass. This prevents the model from becoming too dependent on any specific neurons and forces it to learn more robust, generalizable patterns — reducing overfitting.

Dropout is only active during training. When I switch to eval mode for predictions, it automatically turns off and all neurons contribute fully.

### Training
I'm reusing the exact same `train_classifier` function from Cell 8 revised — which already has the class weighting and `BCEWithLogitsLoss` built in. The only thing I'm changing is running it for **30 epochs** instead of 20, giving the deeper network more time to converge.

### Evaluation
Same approach as before — eval mode, no gradient tracking, threshold at 0.0 on the raw logits, then a full classification report to compare against both the Logistic Regression baseline and the simple neural network.

---

## Summary

This cell tests whether deeper architecture with regularization meaningfully improves on the simpler network. More layers give the model more expressive power, and Dropout keeps it from memorizing the training data. The classification report will tell me if that extra complexity was worth it.
"""

# ============================================================
# Cell 9: Deep Neural Network - Classification
# Multiple hidden layers with Dropout to prevent overfitting
# ============================================================

class DeepClassifierNN(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 1)
        )

    def forward(self, x):
        return self.network(x).squeeze()


deep_clf_nn = DeepClassifierNN(input_dim)
deep_clf_nn, deep_clf_losses = train_classifier(
    deep_clf_nn, X_clf_train_s, y_clf_train, epochs=30
)

deep_clf_nn.eval()
with torch.no_grad():
    raw_preds      = deep_clf_nn(torch.FloatTensor(X_clf_test_s))
    y_pred_deep_nn = (raw_preds > 0.0).int().numpy()

print("\n=== Deep Neural Network - Classification Report ===")
print(classification_report(y_clf_test, y_pred_deep_nn,
                             target_names=["No Diabetes", "Diabetes"]))

"""The deep neural network with class weighting achieves a recall of 0.81, a
marginal improvement over the simple NN's 0.80. The added depth and dropout
layers did not produce a dramatic jump in performance, which suggests that
the limiting factor here is not model complexity but rather the nature of
the data itself — these lifestyle survey features can only tell us so much
about diabetes status.

What is encouraging is that the model held its ground across 30 epochs without
overfitting, which shows the dropout layers are doing their job. The class
weighting carried over correctly from the train_classifier function, confirmed
by the loss starting around 0.90.

At this point our classification results are solid. Here is the full picture:

| Model | Recall (Diabetes) | Precision (Diabetes) | F1 | Accuracy |
|---|---|---|---|---|
| Logistic Regression | 0.16 | 0.52 | 0.24 | 0.86 |
| Simple NN (no weighting) | 0.16 | 0.54 | 0.25 | 0.86 |
| Simple NN (with weighting) | 0.80 | 0.30 | 0.44 | 0.72 |
| Deep NN (with weighting) | 0.81 | 0.30 | 0.44 | 0.71 |

# Confusion Matrix for the Deep Neural Network

I'm visualizing exactly where my deep neural network is getting predictions right and where it's getting them wrong — broken down by class. The classification report in Cell 9 gave me the numbers, this cell makes them immediately readable.

---

## Step by Step

### Computing the Confusion Matrix
I'm passing my true labels and my model's predictions into `confusion_matrix`, which produces a 2x2 grid showing four outcomes:

- **Top-left** — True Negatives: correctly predicted No Diabetes
- **Top-right** — False Positives: predicted Diabetes but actually No Diabetes
- **Bottom-left** — False Negatives: predicted No Diabetes but actually Diabetes
- **Bottom-right** — True Positives: correctly predicted Diabetes

### Plotting as a Heatmap
I'm using seaborn's `heatmap` to render the matrix with color intensity — darker red means a higher count. The `annot=True` and `fmt="d"` settings print the raw integer counts inside each cell so the exact numbers are always visible.

### Saving and Displaying
Same as Cell 4 — saving a clean PNG at 150 DPI and displaying it inline.

---

## Summary

This cell gives me the clearest possible picture of my model's failure modes. In a medical context like diabetes prediction, the bottom-left cell — False Negatives — is the most critical number to watch. Those are real patients the model missed entirely, and in practice that carries a much higher cost than a false alarm.
"""

# ============================================================
# Cell 10: Classification Results - Confusion Matrix
# Visualize how well the best model predicts each class
# ============================================================

cm = confusion_matrix(y_clf_test, y_pred_deep_nn)

fig, ax = plt.subplots(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Reds",
            xticklabels=["No Diabetes", "Diabetes"],
            yticklabels=["No Diabetes", "Diabetes"], ax=ax)
ax.set_title("Confusion Matrix - Deep Neural Network (Classification)")
ax.set_xlabel("Predicted Label")
ax.set_ylabel("True Label")

plt.tight_layout()
plt.savefig("confusion_matrix.png", dpi=150)
plt.show()

"""# Confusion Matrix Results

## What the Matrix Is Telling Me

### Breaking Down the Four Numbers

**31,208 — True Negatives (top-left)**
These are the No Diabetes cases I got right. The model correctly identified 31,208 people as not having diabetes. This is the strongest number in the matrix and shows the model handles the majority class well.

**12,459 — False Positives (top-right)**
These are people the model flagged as Diabetes when they actually don't have it. That's a meaningful number — roughly 28% of all No Diabetes cases got misclassified. In practice these would be unnecessary follow-ups, but clinically they're the less dangerous error.

**1,509 — False Negatives (bottom-left)**
These are the most concerning number. These are real Diabetes cases the model completely missed and sent home with a clean bill of health. 1,509 people who actually have diabetes were told they don't. In a medical context this is the worst possible outcome.

**5,560 — True Positives (bottom-right)**
These are the Diabetes cases the model correctly caught — 5,560 out of a total of 7,069 actual Diabetes cases. That's a recall of around 79%, which is a significant improvement over the 17% I was getting before the class weighting fix in Cell 8.

---

## The Bigger Picture

The class weighting from Cell 8 revised is clearly working — the model is now actually catching the majority of Diabetes cases rather than ignoring them. But the trade-off is visible too. To catch more Diabetes cases, the model became more aggressive in its predictions overall, which is why the False Positives jumped up to 12,459.

This is the classic **precision vs recall trade-off** — by pushing the model to be more sensitive to Diabetes, I've accepted more false alarms on the No Diabetes side. Whether that trade-off is acceptable depends entirely on the real-world use case, but for a medical screening tool, catching more true cases at the cost of more false alarms is generally the right call.

# Baseline Regression with Linear Regression

Same idea as Cell 7 was for classification — I'm training the simplest possible model first to establish a performance floor for my regression task. Here I'm predicting **BMI** as a continuous number, and Linear Regression is my starting point.

---

## Step by Step

### Training the Model
Linear Regression has no hyperparameters to tune here — I just initialize it, call `.fit()` on my scaled training data, and it's done. It finds the best straight-line relationship between my 20 input features and BMI.

### Making Predictions
I run the trained model on the test set and store the predicted BMI values in `y_pred_linreg`.

### Evaluating with Three Metrics
Unlike classification, regression uses continuous error metrics. I'm reporting three:

- **MAE (Mean Absolute Error)** — the average absolute difference between my predicted BMI and the actual BMI. Easy to interpret — if MAE is 4.2, my predictions are off by 4.2 BMI points on average.

- **RMSE (Root Mean Squared Error)** — similar to MAE but squares the errors before averaging, which means large individual errors get penalized more heavily. Always equal to or larger than MAE.

- **R² (R-squared)** — tells me what proportion of the variance in BMI my model is actually explaining. A score of 1.0 would be perfect, 0.0 means the model is no better than just predicting the mean BMI every time, and negative means it's actively worse than that.

---

## Summary

By the end of this cell I have a baseline set of regression numbers. Every model I build after this — including the neural networks — needs to beat these three metrics to justify the added complexity.
"""

# ============================================================
# Cell 11: Baseline Regression - Linear Regression
# Simplest possible model to establish a performance floor
# ============================================================

lin_reg = LinearRegression()
lin_reg.fit(X_reg_train_s, y_reg_train)
y_pred_linreg = lin_reg.predict(X_reg_test_s)

print("=== Linear Regression - Regression Metrics ===")
print(f"MAE:  {mean_absolute_error(y_reg_test, y_pred_linreg):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_reg_test, y_pred_linreg)):.4f}")
print(f"R2:   {r2_score(y_reg_test, y_pred_linreg):.4f}")

"""# Linear Regression Results

## What the Numbers Are Telling Me

**MAE: 4.3643**
On average, my predicted BMI is off by **4.36 points** from the actual value. To put that in context, the difference between a BMI of 25 (healthy) and 29 (overweight) is just 4 points — so this level of error is large enough to potentially misclassify someone's entire weight category.

**RMSE: 6.1749**
The RMSE is noticeably higher than the MAE, which tells me there are some predictions where the model is significantly off — not just slightly wrong across the board. The gap between the two metrics is a sign of outliers pulling the RMSE up.

**R²: 0.1230**
This is the most telling number. At just **12.3%**, the model is only explaining a tiny fraction of the variation in BMI across people. That means roughly 88% of what makes one person's BMI different from another's is not being captured by a simple linear relationship with these features.

---

## What This Means Going Forward

These are weak results, but that's exactly what a baseline is for. The low R² in particular tells me that BMI doesn't have a simple linear relationship with the health indicator features in this dataset — which is actually useful information. It suggests that a more expressive model like a neural network, which can learn non-linear patterns, has real room to improve on this. These three numbers are now my target to beat.

# Simple Neural Network for Regression

Same progression as I did for classification — I'm now building a simple one-hidden-layer neural network for the regression task to see if it can beat the Linear Regression baseline from Cell 11.

---

## Step by Step

### The Architecture
The structure is deliberately simple and mirrors the classification network from Cell 8, with one key difference at the output:

- **Input → 64 neurons → ReLU**
- **64 → 1 output neuron — no activation function**

That last point is critical. In classification I used Sigmoid to squeeze output between 0 and 1. Here I need the model to predict any continuous BMI value, so I leave the output completely unconstrained. A raw linear output is exactly what regression needs.

### The Training Function
I'm writing a separate `train_regressor` function — similar structure to `train_classifier` but with two important differences:

- **No class weighting** — that was specific to the classification imbalance problem. Regression doesn't have that concern.
- **MSELoss instead of BCEWithLogitsLoss** — Mean Squared Error is the standard loss function for regression. It penalizes larger prediction errors more heavily, which pushes the model to avoid big misses on BMI.

Everything else — Adam optimizer, batch size of 512, shuffling, loss tracking per epoch — stays the same.

### Evaluation
After training I switch to eval mode, run predictions on the test set, and report the same three metrics as Cell 11 — MAE, RMSE, and R². This gives me a direct apples-to-apples comparison against the Linear Regression baseline.

---

## Summary

This cell tests whether a neural network with just one hidden layer can capture non-linear relationships in the data that Linear Regression couldn't. Given how low the R² was in Cell 11, there's real room for improvement here.
"""

# ============================================================
# Cell 12: Simple Neural Network - Regression
# One hidden layer, linear output for continuous prediction
# ============================================================

class SimpleRegressorNN(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 1)
        )

    def forward(self, x):
        return self.network(x).squeeze()


def train_regressor(model, X_train, y_train, epochs=20, learning_rate=0.001):
    """Train a regression neural network and return loss history."""

    dataset   = TensorDataset(
        torch.FloatTensor(X_train),
        torch.FloatTensor(y_train.values)
    )
    loader    = DataLoader(dataset, batch_size=512, shuffle=True)
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
    loss_fn   = nn.MSELoss()
    loss_history = []

    model.train()
    for epoch in range(epochs):
        epoch_loss = 0
        for X_batch, y_batch in loader:
            optimizer.zero_grad()
            predictions = model(X_batch)
            loss = loss_fn(predictions, y_batch)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()

        avg_loss = epoch_loss / len(loader)
        loss_history.append(avg_loss)
        print(f"Epoch {epoch+1:02d}/{epochs} - Loss: {avg_loss:.4f}")

    return model, loss_history


reg_input_dim = X_reg_train_s.shape[1]
simple_reg_nn = SimpleRegressorNN(reg_input_dim)
simple_reg_nn, simple_reg_losses = train_regressor(simple_reg_nn, X_reg_train_s, y_reg_train)

simple_reg_nn.eval()
with torch.no_grad():
    y_pred_simple_reg = simple_reg_nn(torch.FloatTensor(X_reg_test_s)).numpy()

print("\n=== Simple Neural Network - Regression Metrics ===")
print(f"MAE:  {mean_absolute_error(y_reg_test, y_pred_simple_reg):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_reg_test, y_pred_simple_reg)):.4f}")
print(f"R2:   {r2_score(y_reg_test, y_pred_simple_reg):.4f}")

"""# Simple Neural Network Regression Results

## Training Loss

```
Epoch 01/20 - Loss: 403.8691
Epoch 02/20 - Loss:  56.0923
Epoch 03/20 - Loss:  43.6763
Epoch 04/20 - Loss:  40.7059
Epoch 05/20 - Loss:  39.3782
Epoch 06/20 - Loss:  38.7383
Epoch 07/20 - Loss:  38.3737
Epoch 08/20 - Loss:  38.0702
Epoch 09/20 - Loss:  37.7473
Epoch 10/20 - Loss:  37.4951
Epoch 11/20 - Loss:  37.3496
Epoch 12/20 - Loss:  37.2039
Epoch 13/20 - Loss:  37.1453
Epoch 14/20 - Loss:  37.0959
Epoch 15/20 - Loss:  37.0414
Epoch 16/20 - Loss:  36.9942
Epoch 17/20 - Loss:  36.9782
Epoch 18/20 - Loss:  36.9593
Epoch 19/20 - Loss:  36.9770
Epoch 20/20 - Loss:  36.9281
```

The loss starts extremely high at 403 because MSELoss operates on raw BMI values which have a much larger scale than binary classification outputs. It crashes down sharply in the first two epochs, then continues improving steadily but slows significantly after Epoch 6. By the final epochs it's essentially plateaued — a sign the model has likely reached the limit of what this architecture can learn.

---

## Regression Metrics

```
MAE:  4.2722
RMSE: 6.0696
R²:   0.1527
```

---

## What the Numbers Are Telling Me

**MAE: 4.2722 vs 4.3643 (Linear Regression)**
A small but real improvement. On average I'm now off by 4.27 BMI points instead of 4.36 — the neural network is making slightly more accurate predictions per case.

**RMSE: 6.0696 vs 6.1749 (Linear Regression)**
Again a modest improvement. The gap between MAE and RMSE is still notable, meaning there are still some individual predictions that are significantly off — but fewer extreme misses than before.

**R²: 0.1527 vs 0.1230 (Linear Regression)**
Up from 12.3% to 15.3% — the model is explaining a bit more of the variance in BMI now. It's a step in the right direction but still low overall, which tells me the relationship between these health indicators and BMI is genuinely complex and likely needs more model capacity to capture properly.

---

## Summary

The simple neural network beats the Linear Regression baseline across all three metrics, which confirms that there are non-linear patterns in the data worth capturing. But the gains are modest, and the R² is still low — which is exactly the motivation for stepping up to a deeper network in the next cell.

# Deep Neural Network for Regression

## What I'm Doing

I'm stepping up to a deeper, more sophisticated network for the regression task — the same progression I made in Cell 9 for classification. This time I'm also introducing **Batch Normalization**, which I didn't use in the classification network, to help stabilize training across the deeper layers.

---

## Step by Step

### The Architecture
Four layers deep, funneling down progressively:

- **Input → 128 neurons → BatchNorm → ReLU → Dropout**
- **128 → 64 neurons → BatchNorm → ReLU → Dropout**
- **64 → 32 neurons → ReLU**
- **32 → 1 output — no activation**

### Batch Normalization
This is the key addition over the classification deep network. After each of the first two linear layers, I'm normalizing the outputs across the batch before passing them through ReLU. This does two things:

- **Stabilizes training** — keeps the values flowing through the network in a consistent range, preventing any one layer from producing wildly large or small values that destabilize the layers after it
- **Speeds up convergence** — because each layer receives well-scaled inputs, the network tends to learn faster and more reliably

This is particularly useful here because BMI is a continuous value with real scale — unlike binary classification outputs, regression targets can vary widely and Batch Normalization helps the network handle that.

### Dropout
Same as Cell 9 — 30% dropout after the first two hidden layers to prevent overfitting and force the model to generalize rather than memorize.

### Training and Evaluation
I'm reusing the same `train_regressor` function from Cell 12, just running it for **30 epochs** to give the deeper network more time to converge. Evaluation is the same three metrics — MAE, RMSE, R² — compared directly against both the Linear Regression baseline and the simple neural network.

---

## Summary

This is the most capable regression model I've built so far. The added depth gives it more capacity to learn complex patterns, Batch Normalization keeps training stable, and Dropout keeps it from overfitting. The metrics will tell me whether that added complexity actually translates to meaningfully better BMI predictions.
"""

# ============================================================
# Cell 13: Deep Neural Network - Regression
# Batch normalization for stable training, dropout for generalization
# ============================================================

class DeepRegressorNN(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 64),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 1)
        )

    def forward(self, x):
        return self.network(x).squeeze()


deep_reg_nn = DeepRegressorNN(reg_input_dim)
deep_reg_nn, deep_reg_losses = train_regressor(
    deep_reg_nn, X_reg_train_s, y_reg_train, epochs=30
)

deep_reg_nn.eval()
with torch.no_grad():
    y_pred_deep_reg = deep_reg_nn(torch.FloatTensor(X_reg_test_s)).numpy()

print("\n=== Deep Neural Network - Regression Metrics ===")
print(f"MAE:  {mean_absolute_error(y_reg_test, y_pred_deep_reg):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_reg_test, y_pred_deep_reg)):.4f}")
print(f"R2:   {r2_score(y_reg_test, y_pred_deep_reg):.4f}")

"""# Deep Neural Network Regression Results

## Regression Metrics

```
MAE:  4.2132
RMSE: 6.0281
R²:   0.1642
```

---

## What the Numbers Are Telling Me

**MAE: 4.2132 vs 4.2722 (Simple NN) vs 4.3643 (Linear Regression)**
Another step forward. I'm now off by 4.21 BMI points on average — a small but consistent improvement across all three models. Each step up in complexity has chipped away at this number.

**RMSE: 6.0281 vs 6.0696 (Simple NN) vs 6.1749 (Linear Regression)**
Continuing to improve. The gap between MAE and RMSE is still present, meaning there are still some individual predictions that are significantly off, but the deep network is handling those outlier cases slightly better than its predecessors.

**R²: 0.1642 vs 0.1527 (Simple NN) vs 0.1230 (Linear Regression)**
Up to 16.4% from 15.3% — the model is explaining more variance in BMI with each step up in complexity. But the honest read here is that even the best model I've built is only explaining about 1 in 6 points of variation in BMI. That's a consistent pattern across all three models.

---

## The Bigger Picture

Every model has improved on the one before it, which confirms that deeper architecture with Batch Normalization and Dropout is genuinely helping. But the ceiling seems low regardless of model complexity. The likely explanation is that **BMI isn't strongly predictable from these particular health indicator features alone** — the dataset simply may not contain enough of the right information to predict BMI with high accuracy. That's not a modeling failure, it's a data limitation, and it's a valid and important finding in itself.

# Predicted vs Actual BMI Plot

## What I'm Doing

The regression metrics in Cell 13 told me the numbers. Now I'm visualizing the actual predictions against the real BMI values to see the model's behavior spatially — where it's performing well and where it's struggling.

---

## Step by Step

### The Scatter Plot
I'm plotting **1,000 samples** from the test set — actual BMI on the x-axis, predicted BMI on the y-axis. Each dot is one person. I'm only using 1,000 instead of the full test set purely for visual clarity — 50,000 dots would turn into a solid blob.

### The Perfect Prediction Line
I'm drawing a red dashed diagonal line from BMI 10 to BMI 80. This represents what a **perfect model would look like** — every prediction exactly matching the actual value. The closer my scatter points cluster around this line, the better the model is performing.

### What to Look For
- **Points tight around the diagonal** — good predictions
- **Points spread vertically away from the line** — the model is wrong on those cases
- **Systematic bias** — if points consistently sit above or below the line across a range of BMI values, the model is structurally over or under-predicting in that region
- **Fan-shaped spread** — if the scatter widens at higher BMI values, the model struggles more with extreme cases

---

## Summary

This plot turns the abstract R² and MAE numbers into something I can actually see and reason about. A number like R²=0.16 is hard to intuit — but seeing how far the scatter cloud sits from the diagonal line makes the model's limitations immediately obvious and concrete.
"""

# ============================================================
# Cell 14: Regression Results - Predicted vs Actual BMI
# A good model should cluster tightly around the diagonal line
# ============================================================

fig, ax = plt.subplots(figsize=(6, 6))

ax.scatter(y_reg_test[:1000], y_pred_deep_reg[:1000],
           alpha=0.4, color="steelblue", s=15, label="Predictions")
ax.plot([10, 80], [10, 80], "r--", linewidth=1.5, label="Perfect Prediction")

ax.set_xlabel("Actual BMI")
ax.set_ylabel("Predicted BMI")
ax.set_title("Predicted vs Actual BMI - Deep Neural Network")
ax.legend()

plt.tight_layout()
plt.savefig("bmi_pred_vs_actual.png", dpi=150)
plt.show()

"""# Predicted vs Actual BMI Results

## What the Plot Is Telling Me

### Where the Model Works
In the **20–35 BMI range** the scatter is densest and closest to the diagonal line. This makes sense — the vast majority of the dataset falls in this range, so the model has seen enough examples there to make reasonably calibrated predictions.

### Where the Model Breaks Down

**For low BMI values (below 20)**
The model is significantly over-predicting. People with a BMI of 15 or 16 are getting predicted values of 24–30. The model has almost no examples of very lean people in training, so it pulls predictions toward the center of the distribution it knows best.

**For high BMI values (above 40)**
The opposite problem — the model is heavily under-predicting. Someone with an actual BMI of 70–80 is getting a predicted value of only 27–30. The scatter drifts further and further below the diagonal as actual BMI increases, which is a clear sign the model has no real concept of extreme obesity.

### The Horizontal Band Pattern
The most telling visual feature is that predictions are essentially **compressed into a horizontal band between roughly 24 and 37** regardless of what the actual BMI is. This means the model has learned the average BMI range well but is failing to capture the full range of variation — it's regressing toward the mean rather than truly predicting individual BMI.

---

## Summary

This plot makes the R² of 0.16 from Cell 13 completely intuitive. The model isn't useless — it's picking up a general signal — but it's clearly unable to handle the extremes of the BMI distribution. To do better I'd likely need either richer features, more data on extreme BMI cases, or a fundamentally different modeling approach.

# Training Loss Curves

I'm plotting how each model's loss changed across every epoch of training — side by side for classification and regression. This gives me a visual audit of the training process itself, not just the final results.

---

## Step by Step

### Two Side-by-Side Plots
I'm creating one figure with two panels:

- **Left panel** — Classification loss curves for both the Simple NN and Deep NN, measured in BCE Loss
- **Right panel** — Regression loss curves for both the Simple NN and Deep NN, measured in MSE Loss

Each panel overlays both models in different colors — steel blue for Simple NN and crimson for Deep NN — so I can directly compare how they trained against each other.

### What I'm Looking For in Each Curve

- **Sharp early drop** — healthy. Means the model is learning quickly in the first few epochs as it picks up the most obvious patterns
- **Smooth, gradual decline** — good. The model is continuing to improve steadily
- **Flat plateau** — the model has converged and stopped learning meaningfully. Expected toward the end
- **Loss going back up** — would signal overfitting. The model is memorizing training data and losing generalization
- **One model consistently lower than the other** — tells me which architecture trained more effectively

---

## Summary

These curves tell me the story of how each model learned, not just where it ended up. A good final metric with a bad loss curve — like one that spiked or never properly converged — would be a red flag worth investigating. This is the last diagnostic check before I move to the final summary comparison.
"""

# ============================================================
# Cell 15: Training Loss Curves
# Shows how each model improved during training over epochs
# ============================================================

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

axes[0].plot(simple_clf_losses, label="Simple NN", color="steelblue")
axes[0].plot(deep_clf_losses,   label="Deep NN",   color="crimson")
axes[0].set_title("Classification - Training Loss")
axes[0].set_xlabel("Epoch")
axes[0].set_ylabel("BCE Loss")
axes[0].legend()

axes[1].plot(simple_reg_losses, label="Simple NN", color="steelblue")
axes[1].plot(deep_reg_losses,   label="Deep NN",   color="crimson")
axes[1].set_title("Regression - Training Loss")
axes[1].set_xlabel("Epoch")
axes[1].set_ylabel("MSE Loss")
axes[1].legend()

plt.tight_layout()
plt.savefig("training_loss_curves.png", dpi=150)
plt.show()

"""# Training Loss Curves Results

## Classification (Left Panel)

**Both models start around 0.90–0.95 BCE Loss and drop sharply in the first 5 epochs**, then continue declining gradually before flattening out around 0.86. A few things stand out:

**The Simple NN trains faster and lower.** It reaches its plateau earlier and consistently sits below the Deep NN throughout training. This is actually a common and legitimate outcome — on structured tabular data like this, a simpler architecture sometimes trains more efficiently than a deeper one because there's less complexity to optimize through.

**The Deep NN converges more slowly.** It starts higher and takes longer to come down, which makes sense — more layers mean more parameters to coordinate during learning. By epoch 30 it's catching up but hasn't fully closed the gap.

**Neither curve shows any upward spike**, which means neither model is overfitting — the Dropout layers in the Deep NN are doing their job.

---

## Regression (Right Panel)

**The dominant feature here is the massive drop in epoch 1** — both models crash from 400 and 200 respectively down to around 50 almost instantly. This is normal for MSE Loss on raw BMI values as I noted in Cell 12 — the scale is just much larger than BCE.

**After epoch 1 both models are nearly identical**, running almost on top of each other for the rest of training. The Deep NN edges slightly lower by epoch 30, which matches the marginal metric improvements I saw in Cell 13.

**Both curves are smooth with no instability**, which confirms the Batch Normalization in the Deep NN is doing its job of keeping training stable across the deeper layers.

---

## Summary

The curves confirm that all four models trained healthily with no overfitting or instability. The interesting finding is that for classification, the Simple NN actually trained to a lower loss than the Deep NN — a reminder that more complexity doesn't always win, especially on tabular data.
"""